apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pet
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saveliypodvolotskiy-pet/pet-k3s-gitops.git
    targetRevision: main
    path: apps/pet
  destination:
    server: https://kubernetes.default.svc
    namespace: pet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
